spring:
  profiles:
    active: local
  config:
    import: application-naver-client.yml
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create # TODO: 추후 옵션 변경, 운영시 create, create-drop은 사용하면 안됨